//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprijenok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Articul { get; set; }
        public int Person { get; set; }
        public int WorkShopNumber { get; set; }
        public int MinPrice { get; set; }
    
        public virtual TypeOfProduct TypeOfProduct { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
